version: "3.9"
services:
  web:
    image: nginx:alpine
    container_name: static-site
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html  # Maps the current directory
    restart: always
